name: lamp-template
services:
  web:
    build:
      context: .
      # .envの値をDockerfileに渡す。
      args:
        APACHE_DOCUMENT_ROOT: ${APACHE_DOCUMENT_ROOT}
    # 127.0.0.1 に限定し、LAN など外部から接続されないようにする
    ports: ["127.0.0.1:8080:80"]
    volumes: ["../..:${APACHE_DOCUMENT_ROOT}"]
    # Linuxで動かすのに必須
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  db:
    # 8.0 最も実績が豊富なバージョン
    image: mysql:8.0
    # ホストの DB クライアント用。127.0.0.1 に限定する
    ports: ["127.0.0.1:3306:3306"]
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appdb
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: